language: python
python:
  - "2.7"
sudo: false

cache:
  - pip
  - directories:
    - node_modules
    - programs/static/bower_components
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -U pip wheel codecov
  - pip install -r requirements/test.txt
  - make requirements.js
script:
    # Compile assets and run validation
  - make static -e DJANGO_SETTINGS_MODULE="programs.settings.test"
  - make validate
after_success:
  - codecov
