language: python
python:
  - "2.7"
sudo: required
services:
  - docker

cache:
  - pip

before_install:
  - docker-compose -f docker-compose-travis.yml up -d

script:
  - docker exec programs_testing /edx/app/programs/programs/.travis/run_tests.sh

after_success:
  - pip install -U codecov
  - docker exec programs_testing /edx/app/programs/programs/.travis/run_coverage.sh
  - codecov
